/** Demo-only fixtures. No PHI. Used exclusively when NEXT_PUBLIC_USE_MOCK_DATA=true. */

export const MOCK_CONSULTATIONS = [
  {
    id: 'mock-001',
    patient_id: 'pat-001',
    intent: 'Dîner anti-IR ciblé, post-charge glucidique du matin',
    meal_type: 'dinner',
    detected_bottlenecks: { dominant: 'IR', co_dominant: null },
    llm_model: 'claude-sonnet-4-20250514',
    created_at: '2026-07-14T14:30:00Z',
    validated_at: null,
    ebm_summary: { T1_count: 5, T2_count: 3, T3_count: 0 },
  },
  {
    id: 'mock-002',
    patient_id: 'pat-002',
    intent: 'Déjeuner anti-inflammatoire, CRP-us à 2.4',
    meal_type: 'lunch',
    detected_bottlenecks: { dominant: 'INFLAM', co_dominant: null },
    llm_model: 'claude-sonnet-4-20250514',
    created_at: '2026-07-13T09:15:00Z',
    validated_at: '2026-07-13T18:00:00Z',
    ebm_summary: { T1_count: 4, T2_count: 4, T3_count: 1 },
  },
  {
    id: 'mock-003',
    patient_id: 'pat-003',
    intent: 'Petit-déjeuner pro-microbiote post-antibiothérapie',
    meal_type: 'breakfast',
    detected_bottlenecks: { dominant: 'DYSBIOSE', co_dominant: 'INFLAM' },
    llm_model: 'claude-sonnet-4-20250514',
    created_at: '2026-07-12T07:45:00Z',
    validated_at: null,
    ebm_summary: { T1_count: 4, T2_count: 2, T3_count: 2 },
  },
  {
    id: 'mock-004',
    patient_id: 'pat-004',
    intent: 'Déjeuner anti-stéatose hépatique',
    meal_type: 'lunch',
    detected_bottlenecks: { dominant: 'IR', co_dominant: null, phenotypes: ['hepatic_masld'] },
    llm_model: 'claude-opus-4-7',
    created_at: '2026-07-10T12:00:00Z',
    validated_at: '2026-07-10T17:30:00Z',
    ebm_summary: { T1_count: 6, T2_count: 3, T3_count: 0 },
  },
];

export const MOCK_DETAIL: Record<string, unknown> = {
  'mock-001': {
    id: 'mock-001',
    intent: 'Dîner anti-IR ciblé, post-charge glucidique du matin',
    meal_type: 'dinner',
    detected_bottlenecks: {
      scores: [
        { bottleneck_id: 'IR', score: 9, major_hits: 3, moderate_hits: 1, triggered: true, is_dominant: true },
        { bottleneck_id: 'INFLAM', score: 2, major_hits: 0, moderate_hits: 1, triggered: false },
        { bottleneck_id: 'DYSBIOSE', score: 0, major_hits: 0, moderate_hits: 0, triggered: false },
      ],
      dominant: 'IR',
      co_dominant: null,
      rationale: 'Bottleneck dominant unique: IR (score 9, 3 majeurs).',
    },
    selected_levers: [
      { lever_id: 'L_EVOO_PRIMARY', name_fr: 'Huile olive EVOO', ebm_tier: 'T1', tier_for_active_bottleneck: 'T1', role: 'universal_star', expected_effect: 'Anti-inflammatory', rationale: 'PREDIMED secondary analysis' },
      { lever_id: 'L_VINEGAR_PRE_PRANDIAL', name_fr: 'Vinaigre pré-prandial', ebm_tier: 'T1', tier_for_active_bottleneck: 'T1', role: 'targeted', expected_effect: '-20% AUC glucose', rationale: 'Levier T1 ciblé IR' },
      { lever_id: 'L_FOOD_SEQUENCE', name_fr: 'Séquence alimentaire', ebm_tier: 'T1', tier_for_active_bottleneck: 'T1', role: 'targeted', expected_effect: '-29% pic glucose', rationale: 'Levier T1 ciblé IR' },
      { lever_id: 'L_POSTPRANDIAL_WALK', name_fr: 'Marche postprandiale', ebm_tier: 'T1', tier_for_active_bottleneck: 'T1', role: 'targeted', expected_effect: '-20% pic glucose', rationale: 'Levier T1 ciblé IR' },
      { lever_id: 'L_LEGUMINOUSES_REGULAR', name_fr: 'Légumineuses', ebm_tier: 'T1', tier_for_active_bottleneck: 'T1', role: 'universal_star', expected_effect: 'HbA1c -0.48%', rationale: 'Sievenpiper méta' },
      { lever_id: 'L_RESISTANT_STARCH', name_fr: 'Amidon résistant', ebm_tier: 'T1', tier_for_active_bottleneck: 'T1', role: 'universal_star', expected_effect: '↓ AUC glucose', rationale: 'Sonia 2015' },
      { lever_id: 'L_NUTS_MIX_30G', name_fr: 'Oléagineux', ebm_tier: 'T1', tier_for_active_bottleneck: 'T1', role: 'universal_star', expected_effect: '↓ LDL', rationale: 'Afshin 2014' },
    ],
    output_dish: {
      title: 'Bol méditerranéen anti-IR aux légumineuses, vinaigrette au vinaigre de cidre',
      description: "Dîner ciblant l'insulinorésistance fonctionnelle. Architecture 50/25/25 avec séquence alimentaire intégrée. 6 leviers T1 mobilisés.",
      architecture: { vegetables_pct: 50, protein_pct: 25, lipid_pct: 25 },
      servings: 2,
      total_time_min: 35,
      ebm_summary: { T1_count: 6, T2_count: 1, T3_count: 0 },
      expected_effects: {
        postprandial_2_4h: '↓ pic glycémique -29% (séquence). ↓ AUC glucose 2h -20% (vinaigre pré-prandial). ↑ GLP-1 (légumineuses et séquence).',
        short_term_4_weeks: '↓ HOMA-IR -0.5 attendu. ↓ triglycérides postprandiaux. Stabilisation glycémique inter-repas.',
        long_term_12_weeks: '↓ HbA1c -0.3 à -0.5% si cohérence 3 mois. ↓ TG/HDL ratio. Amélioration sensibilité insulinique.',
      },
      ingredients: [
        { name: 'Lentilles vertes cuites', quantity: '200g', notes: 'Cuites la veille, refroidies 24h' },
        { name: 'Poivron rouge grillé', quantity: '1 pièce' },
        { name: 'Concombre', quantity: '½ pièce' },
        { name: 'Tomates cerises', quantity: '150g' },
        { name: 'Feta de brebis', quantity: '60g', notes: 'Optionnel. Remplacer par avocat si vegan' },
        { name: "Huile d'olive EVOO", quantity: '2 c.s.', notes: 'Dont 1 c.s. à cru en finition' },
        { name: 'Vinaigre de cidre', quantity: '1 c.s.', notes: 'Dilué dans eau, 10 min avant repas' },
        { name: "Mélange d'herbes fraîches", quantity: '1 poignée' },
      ],
      warnings: [],
    },
    warnings: [],
    excluded_levers: [],
    llm_meta: { model: 'claude-sonnet-4-20250514', input_tokens: 2850, output_tokens: 1240, latency_ms: 12400 },
    created_at: '2026-07-14T14:30:00Z',
    validated_at: null,
  },
};

export const MOCK_STATS = {
  total_consultations: 47,
  consultations_this_month: 12,
  patients_count: 18,
  unique_levers_used: 24,
  avg_t1_per_dish: 4.7,
  avg_t2_per_dish: 3.1,
  bottleneck_distribution: [
    { bottleneck: 'IR', count: 22, label: 'Insulinorésistance' },
    { bottleneck: 'INFLAM', count: 15, label: 'Inflammaging' },
    { bottleneck: 'DYSBIOSE', count: 10, label: 'Dysbiose' },
  ],
  top_levers: [
    { lever: 'L_EVOO_PRIMARY', name: 'Huile olive EVOO', count: 45, tier: 'T1' },
    { lever: 'L_LEGUMINOUSES_REGULAR', name: 'Légumineuses', count: 38, tier: 'T1' },
    { lever: 'L_NUTS_MIX_30G', name: 'Oléagineux', count: 32, tier: 'T1' },
    { lever: 'L_FIBER_30G', name: 'Fibres 30-40g/j', count: 29, tier: 'T1' },
    { lever: 'L_CRUCIFEROUS_STEAM', name: 'Crucifères vapeur', count: 27, tier: 'T1' },
    { lever: 'L_FATTY_FISH_2X', name: 'Poisson gras', count: 25, tier: 'T1' },
    { lever: 'L_COFFEE_FILTER', name: 'Café filtre', count: 22, tier: 'T2' },
    { lever: 'L_VINEGAR_PRE_PRANDIAL', name: 'Vinaigre pré-prandial', count: 20, tier: 'T1' },
  ],
  monthly_activity: [
    { month: 'Fév', consultations: 3 },
    { month: 'Mar', consultations: 7 },
    { month: 'Avr', consultations: 9 },
    { month: 'Mai', consultations: 6 },
    { month: 'Juin', consultations: 10 },
    { month: 'Juil', consultations: 12 },
  ],
};
