-- =====================================================================
-- Seed 04 — Culinary levers (v0.1 baseline, ~25 levers)
-- All claims backed by primary references with PMIDs where available
-- =====================================================================

INSERT INTO culinary_levers (id, name_fr, name_en, description, category, expected_effect, ebm_tier, primary_reference, pubmed_ids, dose_or_protocol, cooking_constraint, contraindications, precautions, is_universal_star) VALUES

-- ─── UNIVERSAL STARS (transversal T1, ≥2 bottlenecks) ───────────────
(
  'L_EVOO_PRIMARY',
  'Huile d''olive extra vierge en première intention',
  'Extra virgin olive oil as primary fat',
  'Substitution des graisses saturées et huiles raffinées par EVOO comme principal lipide. Polyphénols (oléocanthal, hydroxytyrosol), MUFA, effet endothélial et anti-inflammatoire.',
  'ingredient',
  '↑ sensibilité insulinique ; ↓ marqueurs inflammation ; modulation favorable microbiote',
  'T1',
  'PREDIMED 2018 / Estruch 2013 NEJM',
  ARRAY['23432189', '29897866'],
  '≥40 ml/jour, dont une part à cru pour préserver polyphénols',
  'Privilégier à cru ; cuisson modérée tolérée (point de fumée ~190°C)',
  NULL,
  ARRAY['Apport calorique à intégrer'],
  true
),
(
  'L_LEGUMINOUSES_REGULAR',
  'Légumineuses 3-4 portions/semaine',
  'Pulses 3-4 servings/week',
  'Lentilles, pois chiches, haricots, fèves. Fibres fermentescibles, amidon résistant, protéines végétales, magnésium, polyphénols.',
  'ingredient',
  '↓ HbA1c -0.48% ; ↑ SCFA fécal ; ↓ inflammation intestinale',
  'T1',
  'Sievenpiper 2009 méta / Jenkins 2012 RCT',
  ARRAY['19465743', '23089999'],
  '3-4 portions de 100-150g cuites/semaine',
  'Trempage 12h + cuisson longue ; enzymes (laurier, kombu) pour tolérance',
  ARRAY['MICI_active_severe'],
  ARRAY['Introduire progressivement si dysbiose installée pour éviter symptômes FODMAP'],
  true
),
(
  'L_RESISTANT_STARCH',
  'Refroidissement amidon ≥24h (riz, pâtes, pomme de terre)',
  'Resistant starch via 24h cooling',
  'Cuisson puis refroidissement minimum 24h au réfrigérateur. Conversion partielle de l''amidon digestible en amidon résistant type 3 (rétrogradation). Fermentation colique → butyrate.',
  'preparation',
  '↓ AUC glucose postprandiale ; ↑ butyrate fécal',
  'T1',
  'Sonia 2015 / Englyst classification / Robertson 2005',
  ARRAY['25825769', '15983189'],
  'Cuire normalement, refroidir ≥24h, consommer froid ou réchauffé doucement (réchauffage modéré préserve la rétrogradation)',
  'Réchauffage <70°C pour préserver l''amidon résistant',
  NULL,
  NULL,
  true
),
(
  'L_PLANT_DIVERSITY_30',
  'Diversité ≥30 plantes différentes/semaine',
  '30+ different plants per week',
  'Légumes, fruits, légumineuses, céréales complètes, herbes, épices, noix, graines comptés comme espèces distinctes.',
  'ingredient',
  '↑ alpha-diversité Shannon microbiote',
  'T1',
  'McDonald 2018 American Gut Project (n=11k)',
  ARRAY['29795809'],
  '≥30 espèces végétales différentes/semaine, herbes/épices comptées',
  NULL,
  NULL,
  ARRAY['Adapter rythme d''introduction si dysbiose sévère ou IBS'],
  true
),
(
  'L_FERMENTED_DAILY',
  'Aliments fermentés diversifiés ≥1 portion/jour',
  'Diversified fermented foods daily',
  'Kéfir, yaourt vivant, choucroute non pasteurisée, kimchi, miso, kombucha, légumes lactofermentés. Diversité plus importante que quantité.',
  'fermentation',
  '↑ diversité microbiote +10% ; ↓ 19 marqueurs inflammation',
  'T1',
  'Wastyk 2021 RCT Cell Host Microbe',
  ARRAY['34256014'],
  '≥1 portion/jour, tournante entre 4-6 sources différentes',
  'Privilégier fermentés non pasteurisés (raw)',
  ARRAY['immunosuppression_severe'],
  ARRAY['Histamine-sensitive : adapter sources fermentées'],
  true
),
(
  'L_FATTY_FISH_2X',
  'Poisson gras 2-3 portions/semaine',
  'Fatty fish 2-3 servings/week',
  'Saumon, sardine, maquereau, hareng, anchois. Apport EPA+DHA chaînes longues, vit D, sélénium, iode.',
  'ingredient',
  '↓ CRP-us ; ↓ IL-6 ; ↑ Omega-3 Index',
  'T1',
  'Calder 2018 / Wei 2024 méta CRP',
  ARRAY['29610056'],
  '2-3 portions de 100-150g/semaine ; privilégier petits poissons (sardine, maquereau, anchois) pour limiter Hg',
  'Cuisson douce vapeur ou papillote ; éviter friture',
  NULL,
  ARRAY['Grossesse/allaitement : éviter gros poissons (thon, espadon, requin)', 'Anticoagulants : surveillance'],
  true
),
(
  'L_CRUCIFEROUS_STEAM',
  'Crucifères vapeur courte (≤4 min)',
  'Cruciferous steamed ≤4 min',
  'Brocoli, chou-fleur, chou kale, choux de Bruxelles, roquette. Cuisson vapeur courte préserve myrosinase active → conversion glucoraphanine en sulforaphane.',
  'cooking',
  '↓ NF-κB ; ↑ Nrf2 ; soutien voies de détoxification phase II',
  'T1',
  'Vermeulen 2008 (cuisson) / Riedl 2009',
  ARRAY['18975959'],
  '4-5 portions/semaine de 100g, vapeur ≤4 min',
  'Vapeur ≤4 min impérative pour préserver myrosinase ; OU consommer cru avec moutarde fraîche pour réactiver myrosinase exogène',
  NULL,
  ARRAY['Hypothyroïdie sévère : modérer crucifères crues volumineuses'],
  true
),
(
  'L_ANTHOCYANIN_BERRIES',
  'Anthocyanes 200-400g/semaine (baies)',
  'Anthocyanin berries 200-400g/week',
  'Myrtilles, framboises, mûres, cerises, fraises, cassis. Anthocyanes, ellagitannins, polyphénols.',
  'ingredient',
  '↓ CRP ; ↓ IL-6 ; soutien cognition',
  'T1',
  'Joseph 2014 / Krikorian 2010',
  ARRAY['20047325'],
  '200-400g/semaine, frais ou décongelés (congélation préserve anthocyanes)',
  'Cru ou cuisson très douce ; anthocyanes thermolabiles >70°C',
  NULL,
  NULL,
  true
),

-- ─── IR-SPECIFIC LEVERS ────────────────────────────────────────────
(
  'L_VINEGAR_PRE_PRANDIAL',
  'Vinaigre pré-prandial 15-30 ml',
  'Pre-prandial vinegar 15-30 ml',
  'Vinaigre de cidre ou de vin rouge dilué dans 100-150 ml d''eau, 10 minutes avant le repas glucidique. Inhibition partielle alpha-amylase.',
  'timing',
  '-20% AUC glucose 2h ; ↑ satiété',
  'T1',
  'Méta-analyse Shishehbor 2017 / Liljeberg 1998',
  ARRAY['28614524', '9550432'],
  '15-30 ml dilués dans 100-150 ml d''eau, 10 min avant le repas',
  NULL,
  ARRAY['gastritis_active', 'reflux_severe'],
  ARRAY['Reflux : à modérer ; émail dentaire : rincer après'],
  false
),
(
  'L_FOOD_SEQUENCE',
  'Séquence alimentaire : légumes → protéines → glucides',
  'Food sequence: vegetables → proteins → carbs',
  'Consommer dans cet ordre avec ~10 min entre chaque phase si possible. Effet via ralentissement vidange gastrique + sécrétion GLP-1 anticipée.',
  'sequence',
  '-29% pic glucose postprandial',
  'T1',
  'Shukla 2015 / Imai 2014 RCT',
  ARRAY['26106234'],
  'Légumes 5 min, puis protéines 5 min, puis glucides',
  NULL,
  NULL,
  ARRAY['Adapter à contexte social ; effort réaliste : commencer par légumes en entrée'],
  false
),
(
  'L_WHEY_PRE_LOAD',
  'Whey 20g pré-prandial (15 min avant repas glucidique)',
  'Pre-load whey 20g 15 min before',
  'Whey isolate hydrolysat ou concentré, 20g dans eau, 15 min avant repas riche en glucides. Stimulation GLP-1.',
  'timing',
  '-28% pic glucose ; ↑ GLP-1',
  'T2',
  'Jakubowicz 2014 RCT / Hutchison 2015',
  ARRAY['25001580'],
  '20g whey + 200 ml eau, 15 min avant repas glucidique',
  NULL,
  ARRAY['allergy_milk_protein'],
  ARRAY['Insuffisance rénale sévère : modérer charge protéique'],
  false
),
(
  'L_LONG_FERMENTATION_BREAD',
  'Pain à fermentation longue 12-24h (levain)',
  'Long-fermentation sourdough 12-24h',
  'Pain au levain naturel, fermentation ≥12h. Hydrolyse partielle de l''amidon, acidification, pré-digestion FODMAP, acide phytique réduit.',
  'fermentation',
  '↓ IG du pain de 20-30% ; ↓ FODMAP ; ↑ tolérance digestive',
  'T2',
  'De Angelis 2007 / Scazzina 2009 / Laatikainen 2017',
  ARRAY['28829981'],
  'Levain naturel, fermentation ≥12h ; éviter pain industriel à levure rapide',
  NULL,
  ARRAY['celiac_disease'],
  NULL,
  false
),
(
  'L_POSTPRANDIAL_WALK',
  'Marche 10-15 min postprandiale',
  'Post-meal walk 10-15 min',
  'Marche d''intensité légère immédiatement après le repas. Captage musculaire glucose GLUT-4 indépendant insuline.',
  'timing',
  '-20% pic glucose postprandial',
  'T1',
  'Reynolds 2016 / Buffey 2022 méta',
  ARRAY['27747394'],
  '10-15 min minimum, dans les 15 min suivant la fin du repas',
  NULL,
  NULL,
  NULL,
  false
),
(
  'L_WHOLE_GRAINS',
  'Substitution farines raffinées → céréales complètes',
  'Whole grains over refined',
  'Riz complet, pâtes complètes, sarrasin, quinoa, avoine, millet à la place des versions raffinées.',
  'ingredient',
  '↓ pic glycémique ; ↓ HbA1c ; ↓ incidence T2D dose-dépendante',
  'T1',
  'Aune 2013 méta dose-response',
  ARRAY['24230488'],
  'Substitution progressive ; cible >50% des glucides en complets',
  NULL,
  ARRAY['celiac_disease', 'IBS_severe'],
  ARRAY['Phytates : tremper ou rincer si sensibilité'],
  false
),

-- ─── INFLAM-SPECIFIC LEVERS ────────────────────────────────────────
(
  'L_TURMERIC_PIPERINE_LIPID',
  'Curcuma + pipérine + lipide chaud',
  'Turmeric + piperine + warm lipid',
  'Curcumine biodisponibilité multipliée x2000 par pipérine (Shoba 1998, n=8). Solubilisation lipidique requise. Cuisson dans EVOO chaud avec poivre noir.',
  'preparation',
  '↓ CRP-us ; effet anti-inflammatoire systémique',
  'T2',
  'Shoba 1998 / Sahebkar 2016 méta',
  ARRAY['9619120', '27259976'],
  '0.5-1 g curcuma/jour + 1/4 c.c. poivre noir + cuisson dans EVOO ou ghee chaud',
  'Chauffage modéré dans matrice lipidique ; éviter ébullition prolongée',
  ARRAY['anticoagulants_high_dose', 'gallstones_active', 'pre_surgery_2_weeks'],
  ARRAY['AVK : INR surveillance ; AOD : prudence ; arrêt 14j avant chirurgie'],
  false
),
(
  'L_MED_DIET_FULL',
  'Régime méditerranéen complet (pattern)',
  'Full Mediterranean dietary pattern',
  'Pattern global : EVOO + légumes + légumineuses + céréales complètes + poisson + noix + vin rouge modéré (optionnel) + faible viande rouge/transformée.',
  'ingredient',
  '↓ CRP-us moyen 0.98 mg/L ; ↓ événements CV',
  'T1',
  'Schwingshackl 2014 méta / PREDIMED',
  ARRAY['25048037'],
  'Pattern global, pas un aliment isolé',
  NULL,
  NULL,
  NULL,
  false
),
(
  'L_REDUCE_RED_PROCESSED_MEAT',
  'Réduction viande rouge transformée <100g/semaine',
  'Reduce processed red meat <100g/week',
  'Charcuterie, viandes transformées (jambon, saucisse, bacon, saucisson). Pro-inflammatoire, AGE, nitrites, fer héminique en excès.',
  'avoidance',
  '↓ CRP ; ↓ mortalité toutes causes',
  'T1',
  'Rohrmann 2013 / Pan 2012 cohortes',
  ARRAY['23497300'],
  'Viande rouge fraîche : ≤350g/semaine. Viande transformée : <100g/semaine',
  NULL,
  NULL,
  NULL,
  false
),
(
  'L_GREEN_TEA_DAILY',
  'Thé vert 3-4 tasses/jour',
  'Green tea 3-4 cups/day',
  'Catéchines (EGCG), L-théanine. Effet anti-inflammatoire modeste mais reproductible.',
  'ingredient',
  '↓ CRP-us modeste',
  'T2',
  'Liu 2018 méta',
  ARRAY['29870584'],
  '3-4 tasses/jour, infusion 2-3 min à 80°C',
  'Eau ≤80°C pour préserver catéchines',
  NULL,
  ARRAY['Anémie ferriprive : décaler des repas riches en fer non-héminique de ≥1h'],
  false
),
(
  'L_GENTLE_COOKING',
  'Cuisson douce ≤120°C (vapeur, papillote, basse T°)',
  'Gentle cooking ≤120°C',
  'Vapeur, papillote, basse température, mijoté. Limite formation AGE, préserve micronutriments thermolabiles.',
  'cooking',
  '↓ AGE alimentaires (translation clinique débattue)',
  'T2',
  'Uribarri 2010',
  ARRAY['20497781'],
  'Privilégier vapeur, papillote, basse T° ; limiter grillade/friture/barbecue à 1-2x/semaine',
  '≤120°C pour techniques douces ; tolérance jusqu''à 180°C en court',
  NULL,
  NULL,
  false
),

-- ─── DYSBIOSE-SPECIFIC LEVERS ──────────────────────────────────────
(
  'L_PREBIOTIC_TARGETED',
  'Prébiotiques ciblés (chicorée, ail, oignon, poireau, asperge, banane verte, topinambour)',
  'Targeted prebiotics',
  'Inuline, FOS, GOS naturels. Substrats fermentescibles spécifiques ciblant Bifidobactéries.',
  'ingredient',
  '↑ Bifidobactéries ; ↑ SCFA',
  'T1',
  'Holscher 2017 méta',
  ARRAY['28165863'],
  'Introduction progressive : 5g équivalent inuline → 15g/jour sur 4 sem',
  NULL,
  ARRAY['SIBO_active', 'IBS_FODMAP_intolerant'],
  ARRAY['Si SIBO : phase low-FODMAP gradué avant réintroduction'],
  false
),
(
  'L_REDUCE_ULTRA_PROCESSED',
  'Réduction aliments ultra-transformés (<20% calories)',
  'Reduce ultra-processed foods (<20% kcal)',
  'Aliments NOVA-4 : émulsifiants industriels (E407 carraghénane, E466 CMC, polysorbate 80), arômes artificiels, additifs cosmétiques.',
  'avoidance',
  '↓ émulsifiants pro-dysbiotiques ; ↑ diversité microbiote',
  'T2',
  'Chassaing 2015 souris / Whelan 2024 humain',
  ARRAY['25731162'],
  'Cible <20% des calories quotidiennes en aliments ultra-transformés',
  NULL,
  NULL,
  NULL,
  false
),
(
  'L_FIBER_30G',
  'Fibres totales 30-40 g/jour',
  'Total fiber 30-40 g/day',
  'Cible OMS révisée. Mix solubles/insolubles, fermentescibles/non-fermentescibles. Sources : légumineuses, céréales complètes, légumes, fruits, oléagineux.',
  'ingredient',
  '↓ mortalité toutes causes ; ↑ SCFA ; ↓ inflammation systémique',
  'T1',
  'Reynolds 2019 méta Lancet',
  ARRAY['30638909'],
  'Progression 25 → 30 → 40 g/jour sur 6-8 sem si terrain peu habitué',
  NULL,
  ARRAY['MICI_flare_active', 'occlusion_subocclusion'],
  ARRAY['IBS sévère : adapter type fibres (préférer solubles, éviter insolubles brutes)'],
  false
),
(
  'L_AVOID_ARTIFICIAL_SWEETENERS',
  'Éviter édulcorants artificiels (sucralose, saccharine)',
  'Avoid artificial sweeteners',
  'Suez 2014 et 2022 : signal défavorable sur tolérance glucidique et microbiote chez sous-population répondeuse. Préférer monk fruit, stévia, allulose si édulcorant nécessaire.',
  'avoidance',
  '↓ signal défavorable microbiote (sous-population répondeuse)',
  'T2',
  'Suez 2014 Nature / Suez 2022 Cell',
  ARRAY['25231862', '36027326'],
  'Éviter sucralose, saccharine, aspartame en consommation chronique',
  NULL,
  NULL,
  ARRAY['Substitution acceptable : monk fruit, stévia, allulose, tagatose'],
  false
),
(
  'L_BONE_BROTH',
  'Bouillon d''os (mijoté 12-24h)',
  'Bone broth 12-24h simmer',
  'Mijoté long os/cartilages. Apport collagène, glycine, glutamine. Soutien barrière intestinale (mécanistique).',
  'preparation',
  'Soutien barrière intestinale (translation humaine limitée)',
  'T3',
  'Données mécanistiques ; études cliniques humaines limitées',
  NULL,
  '300-500 ml/jour, 3-5 jours/semaine',
  'Mijoté 12-24h, vinaigre dans l''eau pour extraire minéraux',
  NULL,
  ARRAY['Histamine-sensitive : limiter durée de mijotage'],
  false
);

-- ─── ALLOSTATIC LOAD / RECOVERY LEVERS ──────────────────────────────
INSERT INTO culinary_levers (id, name_fr, name_en, description, category, expected_effect, ebm_tier, primary_reference, pubmed_ids, dose_or_protocol, cooking_constraint, contraindications, precautions, is_universal_star) VALUES
(
  'L_GLYCINE_PRE_BED',
  'Glycine 3g avant coucher',
  'Glycine 3g before bedtime',
  'Glycine alimentaire/supplémentaire prise 30-60 min avant le coucher. Substrat inhibiteur et thermorégulateur, signal de downshift nocturne.',
  'timing',
  '↑ qualité subjective du sommeil ; ↓ fatigue liée à restriction de sommeil',
  'T2',
  'Bannai 2012 / Kawai 2015',
  ARRAY['22293292', '22529837'],
  '3g de glycine 30-60 min avant coucher ; option culinaire : bouillon/collagène riche en glycine si toléré',
  NULL,
  NULL,
  ARRAY['Insuffisance rénale sévère : avis médical sur charge azotée totale'],
  false
),
(
  'L_MAGNESIUM_FOOD',
  'Apport magnésium alimentaire ≥350mg/j',
  'Dietary magnesium ≥350mg/day',
  'Graines de courge, amandes/noix, cacao non sucré, épinards, légumineuses. Levier alimentaire de soutien neuromusculaire et sommeil, plus prudent que supplémentation isolée.',
  'ingredient',
  'Association favorable avec qualité du sommeil ; RCT supplémentation hétérogènes',
  'T2',
  'Arab 2022 systematic review',
  ARRAY['35184264'],
  'Viser 300-400mg/j via aliments ; inclure 1 source Mg au dîner ou collation du soir',
  NULL,
  ARRAY['renal_failure_advanced'],
  ARRAY['Supplémentation pharmacologique Mg : prudence insuffisance rénale ; ce levier privilégie les aliments'],
  false
),
(
  'L_KIWI_PRE_BED',
  'Deux kiwis 1h avant coucher',
  'Two kiwifruits 1h before bedtime',
  'Kiwifruit comme collation pré-coucher : matrice glucidique modérée, antioxydants, folates et composés sérotoninergiques. Données humaines initiales sur sommeil.',
  'timing',
  '↓ latence d’endormissement ; ↑ durée/efficacité sommeil dans petite étude',
  'T2',
  'Lin 2011 clinical study',
  ARRAY['21669584'],
  '2 kiwis 1h avant coucher pendant 4 semaines ; adapter si contrainte glycémique ou reflux',
  NULL,
  ARRAY['kiwi_allergy'],
  ARRAY['IR marquée : associer à protéines/lipides ou préférer glycine/Mg'],
  false
),
(
  'L_CAFFEINE_CUTOFF_8H',
  'Arrêt caféine ≥8h avant coucher',
  'Caffeine cutoff ≥8h before bedtime',
  'Éviter café, thé caféiné, maté, cola/énergisants et pré-workouts en seconde partie de journée. La demi-vie de la caféine maintient un tonus sympathique nocturne chez sujets sensibles.',
  'avoidance',
  '↓ fragmentation sommeil ; ↑ durée totale sommeil',
  'T1',
  'Drake 2013 J Clin Sleep Med',
  ARRAY['24235903'],
  'Dernière prise caféine ≥8h avant l’heure cible de sommeil ; ≥10-12h si métaboliseur lent ou sommeil fragile',
  NULL,
  NULL,
  ARRAY['Sevrage progressif si consommation élevée pour éviter céphalées'],
  false
),
(
  'L_PROTEIN_BREAKFAST_STABLE_ENERGY',
  'Petit-déjeuner protéiné 25-35g',
  'Protein-forward breakfast 25-35g',
  'Petit-déjeuner ou premier repas riche en protéines complètes, fibres et lipides stables pour réduire creux énergétique et cravings de fin d’après-midi.',
  'timing',
  '↑ satiété ; ↓ cravings ; stabilisation énergétique diurne',
  'T2',
  'Leidy 2015 / evidence protein breakfast appetite',
  NULL,
  '25-35g protéines au premier repas, avec fibres et lipides ; éviter petit-déjeuner sucré isolé',
  NULL,
  ARRAY['renal_failure_advanced'],
  ARRAY['Adapter quantité à poids, activité et fonction rénale'],
  false
);
