/**
 * Compact culinary catalog for the public demo.
 * IDs, names, tiers and mappings match seed 04/05 (subset) so the selector
 * produces the same kind of output as the practitioner engine.
 */

import type { CulinaryLever, LeverBottleneckMap, LeverCategory } from '@/lib/reasoning/types';

function lever(partial: {
  id: string;
  name_fr: string;
  description: string;
  category: LeverCategory;
  expected_effect: string;
  ebm_tier: 'T1' | 'T2' | 'T3';
  is_universal_star: boolean;
  dose_or_protocol?: string;
  primary_reference?: string;
  pubmed_ids?: string[];
}): CulinaryLever {
  return { active: true, ...partial };
}

export const DEMO_LEVERS: CulinaryLever[] = [
  lever({
    id: 'L_EVOO_PRIMARY',
    name_fr: "Huile d'olive extra vierge en première intention",
    description: 'EVOO comme lipide principal. Polyphénols, MUFA.',
    category: 'ingredient',
    expected_effect: '↑ sensibilité insulinique ; ↓ marqueurs inflammation',
    ebm_tier: 'T1',
    is_universal_star: true,
    dose_or_protocol: '≥40 ml/jour, dont une part à cru',
    primary_reference: 'PREDIMED 2018 / Estruch 2013 NEJM',
    pubmed_ids: ['23432189', '29897866'],
  }),
  lever({
    id: 'L_LEGUMINOUSES_REGULAR',
    name_fr: 'Légumineuses 3-4 portions/semaine',
    description: 'Lentilles, pois chiches, haricots — fibres et amidon résistant.',
    category: 'ingredient',
    expected_effect: '↓ HbA1c -0.48% ; ↑ SCFA fécal',
    ebm_tier: 'T1',
    is_universal_star: true,
    dose_or_protocol: '3-4 portions de 100-150 g cuites/semaine',
    primary_reference: 'Sievenpiper 2009 méta',
    pubmed_ids: ['19465743'],
  }),
  lever({
    id: 'L_RESISTANT_STARCH',
    name_fr: 'Refroidissement amidon ≥24h (riz, pâtes, pomme de terre)',
    description: 'Cuisson puis réfrigérateur ≥24h → amidon résistant type 3.',
    category: 'preparation',
    expected_effect: '↓ AUC glucose postprandiale ; ↑ butyrate fécal',
    ebm_tier: 'T1',
    is_universal_star: true,
    dose_or_protocol: 'Cuire, refroidir ≥24h, consommer froid ou réchauffé doucement',
    primary_reference: 'Sonia 2015 / Robertson 2005',
    pubmed_ids: ['26693746'],
  }),
  lever({
    id: 'L_PLANT_DIVERSITY_30',
    name_fr: 'Diversité ≥30 plantes différentes/semaine',
    description: 'Légumes, fruits, légumineuses, herbes, épices, noix — espèces distinctes.',
    category: 'ingredient',
    expected_effect: '↑ alpha-diversité Shannon microbiote',
    ebm_tier: 'T1',
    is_universal_star: true,
    dose_or_protocol: '≥30 espèces végétales/semaine',
    primary_reference: 'McDonald 2018 American Gut Project',
    pubmed_ids: ['29795809'],
  }),
  lever({
    id: 'L_FERMENTED_DAILY',
    name_fr: 'Aliments fermentés diversifiés ≥1 portion/jour',
    description: 'Kéfir, choucroute crue, kimchi, miso — diversité > quantité.',
    category: 'fermentation',
    expected_effect: '↑ diversité microbiote ; ↓ marqueurs inflammation (Wastyk 2021)',
    ebm_tier: 'T1',
    is_universal_star: true,
    dose_or_protocol: '≥1 portion/jour, sources tournantes',
    primary_reference: 'Wastyk 2021 RCT',
    pubmed_ids: ['34256014'],
  }),
  lever({
    id: 'L_FATTY_FISH_2X',
    name_fr: 'Poisson gras 2-3 portions/semaine',
    description: 'Sardine, maquereau, saumon, hareng — EPA+DHA.',
    category: 'ingredient',
    expected_effect: '↓ CRP-us ; ↓ IL-6 ; ↑ Omega-3 Index',
    ebm_tier: 'T1',
    is_universal_star: true,
    dose_or_protocol: '2-3 portions de 100-150 g/semaine',
    primary_reference: 'Calder 2018 / Wei 2024 méta CRP',
    pubmed_ids: ['29610056'],
  }),
  lever({
    id: 'L_CRUCIFEROUS_STEAM',
    name_fr: 'Crucifères vapeur courte (≤4 min)',
    description: 'Brocoli, kale, chou-fleur — myrosinase / sulforaphane.',
    category: 'cooking',
    expected_effect: '↓ NF-κB ; ↑ Nrf2',
    ebm_tier: 'T1',
    is_universal_star: true,
    dose_or_protocol: '4-5 portions/semaine, vapeur ≤4 min',
    primary_reference: 'Vermeulen 2008',
    pubmed_ids: ['18975959'],
  }),
  lever({
    id: 'L_ANTHOCYANIN_BERRIES',
    name_fr: 'Anthocyanes 200-400 g/semaine (baies)',
    description: 'Myrtilles, mûres, cassis, framboises.',
    category: 'ingredient',
    expected_effect: '↓ CRP ; ↓ IL-6',
    ebm_tier: 'T1',
    is_universal_star: true,
    dose_or_protocol: '200-400 g/semaine, cru ou décongelé',
    primary_reference: 'Joseph 2014 / Krikorian 2010',
    pubmed_ids: ['20047325'],
  }),
  lever({
    id: 'L_VINEGAR_PRE_PRANDIAL',
    name_fr: 'Vinaigre pré-prandial 15-30 ml',
    description: 'Vinaigre dilué 10 min avant le repas glucidique.',
    category: 'timing',
    expected_effect: '-20% AUC glucose 2h ; ↑ satiété',
    ebm_tier: 'T1',
    is_universal_star: false,
    dose_or_protocol: '15-30 ml dans 100-150 ml d’eau, 10 min avant',
    primary_reference: 'Shishehbor 2017 méta',
    pubmed_ids: ['28292654'],
  }),
  lever({
    id: 'L_FOOD_SEQUENCE',
    name_fr: 'Séquence alimentaire : légumes → protéines → glucides',
    description: 'Ordre du repas pour ralentir la vidange gastrique.',
    category: 'sequence',
    expected_effect: '-29% pic glucose postprandial',
    ebm_tier: 'T1',
    is_universal_star: false,
    dose_or_protocol: 'Légumes d’abord, puis protéines, puis glucides',
    primary_reference: 'Shukla 2015 / Imai 2014 RCT',
    pubmed_ids: ['26106234'],
  }),
  lever({
    id: 'L_POSTPRANDIAL_WALK',
    name_fr: 'Marche 10-15 min postprandiale',
    description: 'Captage musculaire glucose GLUT-4 indépendant de l’insuline.',
    category: 'timing',
    expected_effect: '-20% pic glucose postprandial',
    ebm_tier: 'T1',
    is_universal_star: false,
    dose_or_protocol: '10-15 min dans les 15 min suivant le repas',
    primary_reference: 'Reynolds 2016 / Buffey 2022 méta',
    pubmed_ids: ['27747394'],
  }),
  lever({
    id: 'L_WHOLE_GRAINS',
    name_fr: 'Substitution farines raffinées → céréales complètes',
    description: 'Riz complet, sarrasin, quinoa, avoine à la place du raffiné.',
    category: 'ingredient',
    expected_effect: '↓ pic glycémique ; ↓ HbA1c (pattern, pas un plat isolé)',
    ebm_tier: 'T1',
    is_universal_star: false,
    dose_or_protocol: 'Substitution progressive ; cible >50% des glucides en complets',
    primary_reference: 'Aune 2013 méta',
    pubmed_ids: ['24158434'],
  }),
  lever({
    id: 'L_TURMERIC_PIPERINE_LIPID',
    name_fr: 'Curcuma + pipérine + lipide chaud',
    description: 'Curcumine en matrice lipidique avec poivre noir.',
    category: 'preparation',
    expected_effect: '↓ CRP-us (formulation-dépendante)',
    ebm_tier: 'T2',
    is_universal_star: false,
    dose_or_protocol: '0,5–1 g curcuma/j + poivre + EVOO chaud',
    primary_reference: 'Sahebkar 2016 méta',
    pubmed_ids: ['27259976'],
  }),
  lever({
    id: 'L_GREEN_TEA_DAILY',
    name_fr: 'Thé vert 3-4 tasses/jour',
    description: 'Catéchines (EGCG). Décaler des repas riches en fer non-héminique.',
    category: 'ingredient',
    expected_effect: '↓ CRP-us modeste',
    ebm_tier: 'T2',
    is_universal_star: false,
    dose_or_protocol: '3-4 tasses/j, infusion 2-3 min à 80°C',
    primary_reference: 'Haghighatdoost 2019 méta',
    pubmed_ids: ['31309655'],
  }),
  lever({
    id: 'L_GENTLE_COOKING',
    name_fr: 'Cuisson douce ≤120°C (vapeur, papillote)',
    description: 'Limite AGE ; préserve polyphénols thermolabiles.',
    category: 'cooking',
    expected_effect: '↓ AGE alimentaires (translation clinique débattue)',
    ebm_tier: 'T2',
    is_universal_star: false,
    dose_or_protocol: 'Privilégier vapeur / papillote ; limiter grillade',
    primary_reference: 'Uribarri 2010',
    pubmed_ids: ['20497781'],
  }),
  lever({
    id: 'L_PREBIOTIC_TARGETED',
    name_fr: 'Prébiotiques ciblés (ail, poireau, asperge, topinambour)',
    description: 'Inuline / FOS / GOS naturels. Introduction progressive.',
    category: 'ingredient',
    expected_effect: '↑ Bifidobactéries ; ↑ SCFA',
    ebm_tier: 'T1',
    is_universal_star: false,
    dose_or_protocol: 'Introduction progressive sur 4 semaines',
    primary_reference: 'Holscher 2017 méta',
    pubmed_ids: ['28165863'],
  }),
  lever({
    id: 'L_FIBER_30G',
    name_fr: 'Fibres totales 30-40 g/jour',
    description: 'Mix solubles / insolubles. Progression si terrain peu habitué.',
    category: 'ingredient',
    expected_effect: '↑ SCFA ; ↓ inflammation systémique (pattern alimentaire)',
    ebm_tier: 'T1',
    is_universal_star: false,
    dose_or_protocol: 'Progression 25 → 30 → 40 g/j sur 6-8 sem',
    primary_reference: 'Reynolds 2019 méta Lancet',
    pubmed_ids: ['30638909'],
  }),
  lever({
    id: 'L_REDUCE_ULTRA_PROCESSED',
    name_fr: 'Réduction aliments ultra-transformés (<20% calories)',
    description: 'Limiter NOVA-4 et émulsifiants industriels.',
    category: 'avoidance',
    expected_effect: '↓ exposome ultra-transformé ; signal microbiote',
    ebm_tier: 'T2',
    is_universal_star: false,
    dose_or_protocol: 'Cible <20% des calories en ultra-transformé',
    primary_reference: 'Whelan 2024 / Chassaing 2015',
  }),
  lever({
    id: 'L_BONE_BROTH',
    name_fr: "Bouillon d'os (mijoté 12-24h)",
    description: 'Glycine, collagène — soutien barrière (mécanistique).',
    category: 'preparation',
    expected_effect: 'Soutien barrière intestinale (translation humaine limitée)',
    ebm_tier: 'T3',
    is_universal_star: false,
    dose_or_protocol: '300-500 ml, 3-5 j/semaine',
    primary_reference: 'Données mécanistiques ; essais humains limités',
  }),
];

export const DEMO_LEVER_MAP: LeverBottleneckMap[] = [
  { lever_id: 'L_EVOO_PRIMARY', bottleneck_id: 'IR', tier_for_bottleneck: 'T1', priority: 5 },
  { lever_id: 'L_EVOO_PRIMARY', bottleneck_id: 'INFLAM', tier_for_bottleneck: 'T1', priority: 5 },
  { lever_id: 'L_EVOO_PRIMARY', bottleneck_id: 'DYSBIOSE', tier_for_bottleneck: 'T2', priority: 30 },
  { lever_id: 'L_LEGUMINOUSES_REGULAR', bottleneck_id: 'IR', tier_for_bottleneck: 'T1', priority: 10 },
  { lever_id: 'L_LEGUMINOUSES_REGULAR', bottleneck_id: 'INFLAM', tier_for_bottleneck: 'T2', priority: 25 },
  { lever_id: 'L_LEGUMINOUSES_REGULAR', bottleneck_id: 'DYSBIOSE', tier_for_bottleneck: 'T1', priority: 10 },
  { lever_id: 'L_RESISTANT_STARCH', bottleneck_id: 'IR', tier_for_bottleneck: 'T1', priority: 15 },
  { lever_id: 'L_RESISTANT_STARCH', bottleneck_id: 'DYSBIOSE', tier_for_bottleneck: 'T2', priority: 20 },
  { lever_id: 'L_PLANT_DIVERSITY_30', bottleneck_id: 'DYSBIOSE', tier_for_bottleneck: 'T1', priority: 1 },
  { lever_id: 'L_PLANT_DIVERSITY_30', bottleneck_id: 'INFLAM', tier_for_bottleneck: 'T2', priority: 30 },
  { lever_id: 'L_PLANT_DIVERSITY_30', bottleneck_id: 'IR', tier_for_bottleneck: 'T2', priority: 35 },
  { lever_id: 'L_FERMENTED_DAILY', bottleneck_id: 'DYSBIOSE', tier_for_bottleneck: 'T1', priority: 5 },
  { lever_id: 'L_FERMENTED_DAILY', bottleneck_id: 'INFLAM', tier_for_bottleneck: 'T2', priority: 20 },
  { lever_id: 'L_FERMENTED_DAILY', bottleneck_id: 'IR', tier_for_bottleneck: 'T2', priority: 40 },
  { lever_id: 'L_FATTY_FISH_2X', bottleneck_id: 'INFLAM', tier_for_bottleneck: 'T1', priority: 1 },
  { lever_id: 'L_FATTY_FISH_2X', bottleneck_id: 'IR', tier_for_bottleneck: 'T2', priority: 25 },
  { lever_id: 'L_CRUCIFEROUS_STEAM', bottleneck_id: 'INFLAM', tier_for_bottleneck: 'T1', priority: 10 },
  { lever_id: 'L_CRUCIFEROUS_STEAM', bottleneck_id: 'IR', tier_for_bottleneck: 'T2', priority: 40 },
  { lever_id: 'L_CRUCIFEROUS_STEAM', bottleneck_id: 'DYSBIOSE', tier_for_bottleneck: 'T2', priority: 35 },
  { lever_id: 'L_ANTHOCYANIN_BERRIES', bottleneck_id: 'INFLAM', tier_for_bottleneck: 'T1', priority: 12 },
  { lever_id: 'L_ANTHOCYANIN_BERRIES', bottleneck_id: 'IR', tier_for_bottleneck: 'T2', priority: 45 },
  { lever_id: 'L_ANTHOCYANIN_BERRIES', bottleneck_id: 'DYSBIOSE', tier_for_bottleneck: 'T2', priority: 32 },
  { lever_id: 'L_VINEGAR_PRE_PRANDIAL', bottleneck_id: 'IR', tier_for_bottleneck: 'T1', priority: 1 },
  { lever_id: 'L_FOOD_SEQUENCE', bottleneck_id: 'IR', tier_for_bottleneck: 'T1', priority: 2 },
  { lever_id: 'L_POSTPRANDIAL_WALK', bottleneck_id: 'IR', tier_for_bottleneck: 'T1', priority: 3 },
  { lever_id: 'L_WHOLE_GRAINS', bottleneck_id: 'IR', tier_for_bottleneck: 'T1', priority: 8 },
  { lever_id: 'L_TURMERIC_PIPERINE_LIPID', bottleneck_id: 'INFLAM', tier_for_bottleneck: 'T2', priority: 22 },
  { lever_id: 'L_GREEN_TEA_DAILY', bottleneck_id: 'INFLAM', tier_for_bottleneck: 'T2', priority: 25 },
  { lever_id: 'L_GENTLE_COOKING', bottleneck_id: 'INFLAM', tier_for_bottleneck: 'T2', priority: 22 },
  { lever_id: 'L_PREBIOTIC_TARGETED', bottleneck_id: 'DYSBIOSE', tier_for_bottleneck: 'T1', priority: 8 },
  { lever_id: 'L_FIBER_30G', bottleneck_id: 'DYSBIOSE', tier_for_bottleneck: 'T1', priority: 3 },
  { lever_id: 'L_FIBER_30G', bottleneck_id: 'IR', tier_for_bottleneck: 'T1', priority: 12 },
  { lever_id: 'L_FIBER_30G', bottleneck_id: 'INFLAM', tier_for_bottleneck: 'T1', priority: 14 },
  { lever_id: 'L_REDUCE_ULTRA_PROCESSED', bottleneck_id: 'DYSBIOSE', tier_for_bottleneck: 'T2', priority: 15 },
  { lever_id: 'L_REDUCE_ULTRA_PROCESSED', bottleneck_id: 'INFLAM', tier_for_bottleneck: 'T2', priority: 28 },
  { lever_id: 'L_BONE_BROTH', bottleneck_id: 'DYSBIOSE', tier_for_bottleneck: 'T3', priority: 40 },
];
